version: '3'
services:
    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www/bookexchange
        ports:
            - 9999:80

    postgre:
        image: postgres:11-alpine
        environment:
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_USER=${POSTGRES_USER}
        volumes:
          - pgdata:/var/lib/postgresql/data


    php-fpm:
        build:
            context: ./docker/php-fpm
        volumes:
            - ./:/var/www/bookexchange

volumes:
  pgdata: